apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-event-handler
  namespace: eventhandler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-event-handler
subjects:
- kind: ServiceAccount
  name: configmap-event-handler
  namespace: eventhandler

